# Generated by Django 5.2 on 2025-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='blog.comment'),
        ),
    ]
