# Generated by Django 5.2 on 2025-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='comment',
            field=models.ManyToManyField(blank=True, to='blog.comment'),
        ),
    ]
