# Generated by Django 5.2 on 2025-05-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_img_alter_blogs_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='ім`я')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc_all',
            field=models.TextField(blank=True, verbose_name='опис повний'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(verbose_name='опис не повний'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
