# Generated by Django 5.2 on 2025-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_blogs_desc_all_alter_blogs_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото'),
        ),
    ]
