# Generated by Django 5.2 on 2025-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(verbose_name='вид')),
                ('type_people', models.CharField(verbose_name='для кого')),
            ],
        ),
        migrations.AddField(
            model_name='tovars',
            name='type',
            field=models.ManyToManyField(to='main_page.type', verbose_name='вид'),
        ),
    ]
