# Generated by Django 5.2 on 2025-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_type_tovars_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type_people',
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(verbose_name='для кого'),
        ),
    ]
