# Generated by Django 5.2 on 2025-04-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovars',
            name='tag',
            field=models.ManyToManyField(to='main_page.tag', verbose_name='теги'),
        ),
    ]
