# Generated by Django 5.2 on 2025-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_tovars_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skidka_Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_new', models.IntegerField(verbose_name='нова ціна')),
                ('old', models.ManyToManyField(to='main_page.tovars', verbose_name='товар')),
            ],
        ),
    ]
