# Generated by Django 5.2 on 2025-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="ім'я")),
                ('desc', models.TextField(max_length=200, verbose_name='опис')),
                ('job', models.CharField(max_length=30, verbose_name='працівник')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
