# Generated by Django 5.2 on 2025-05-05 07:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_say'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(max_length=100, verbose_name='адреса')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA', verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='пошта')),
            ],
        ),
    ]
