# Generated by Django 5.2 on 2025-05-05 07:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_contatc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(blank=True, max_length=100, verbose_name='адреса')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='UA', verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='пошта')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Get_Contatc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(blank=True, max_length=100, verbose_name='адреса')),
                ('desc', models.TextField(blank=True, max_length=300, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='пошта')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
            ],
        ),
        migrations.DeleteModel(
            name='Contatc',
        ),
    ]
