# Generated by Django 5.2 on 2025-05-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_contact_get_contatc_delete_contatc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='get_contatc',
            old_name='adress',
            new_name='name',
        ),
    ]
