# Generated by Django 5.2 on 2025-05-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_rename_adress_get_contatc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovars',
            name='type',
        ),
        migrations.AddField(
            model_name='tovars',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.type', verbose_name='вид'),
        ),
    ]
