# Generated by Django 5.2 on 2025-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_remove_tovars_type_tovars_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovars',
            name='avaible',
            field=models.IntegerField(null=True, verbose_name='кількість'),
        ),
    ]
