# Generated by Django 5.2 on 2025-05-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_tovars_avaible'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.size', verbose_name='розмір')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tovars', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='Carts_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='main_page.cartitem', verbose_name='позиції')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(null=True, verbose_name='ім’я')),
                ('last_name', models.CharField(null=True, verbose_name='прізвище')),
                ('country', models.CharField(null=True, verbose_name='країна')),
                ('street_adress', models.TextField(null=True, verbose_name='адреса')),
                ('city', models.CharField(null=True, verbose_name='місто')),
                ('postcode', models.IntegerField(null=True, verbose_name='поштовий код')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='пошта')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.carts_order', verbose_name='кошик')),
            ],
        ),
    ]
