# Generated by Django 5.2 on 2025-05-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_adress',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове замовлення'), ('processing', 'Обробка'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено')], default='new', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.TextField(null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='carts_order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='carts_order',
            name='items',
            field=models.ManyToManyField(to='main_page.cartitem', verbose_name='Позиції'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=20, null=True, verbose_name='Поштовий код'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='avaible',
            field=models.IntegerField(default=0, verbose_name='Кількість в наявності'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='desc',
            field=models.TextField(max_length=1000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='manufacter',
            field=models.CharField(max_length=1000, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='main_page.size', verbose_name='Розміри'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='tag',
            field=models.ManyToManyField(to='main_page.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.type', verbose_name='Тип'),
        ),
    ]
