# Generated by Django 5.2 on 2025-05-07 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_remove_order_cart_remove_order_street_adress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='carts_order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.carts_order', verbose_name='Кошик'),
        ),
        migrations.AlterField(
            model_name='carts_order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carts_order',
            name='items',
            field=models.ManyToManyField(to='main_page.cartitem', verbose_name='позиції'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='avaible',
            field=models.IntegerField(null=True, verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='desc',
            field=models.TextField(max_length=1000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='фото товару'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='manufacter',
            field=models.TextField(max_length=1000, verbose_name='мануфактура'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='name',
            field=models.TextField(max_length=30, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='price',
            field=models.IntegerField(verbose_name='ціна'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='main_page.size', verbose_name='розміри'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='tag',
            field=models.ManyToManyField(to='main_page.tag', verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.type', verbose_name='вид'),
        ),
    ]
