# Generated by Django 5.2 on 2025-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_delete_orderitem_carts_order_user_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts_order',
            name='apartment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carts_order',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
