# Generated by Django 5.2 on 2025-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts_order',
            name='status',
            field=models.CharField(default='in_cart', max_length=50, null=True),
        ),
    ]
